### ISSUE TITLE
Video rotation issue

### ISSUE THREAD

**Issue by buscarini** [donmelton/video-transcoding-scripts#9] opened 2015-01-13 16:11 UTC
I'm using this to reduce the size of my Dropbox uploads folder. I have some iPhone videos there, and for some of them this is great, but portrait videos are being rotated to landscape, and some landscape videos are turned upside down. Is there any parameter to avoid this from happening?

Thanks for this scripts, they are very useful

**Comment by donmelton** [comment] 2015-01-13 16:53
Thanks and you are very welcome. I'm glad the scripts are useful to you.

The problem you're seeing is caused by missing metadata, specifically matrix rotation information to compensate for how you were holding your iPhone when you shot the video. HandBrake does not copy this metadata during transcoding so you're videos are sometimes strangely oriented.

If you don't want to re-transcode your videos, you can use a tool like "[Video Rotate](http://www.gadgetjuice.com/)" (in "fast" mode) to apply the rotation metadata after the fact. Keep in mind that not many non-Apple software or hardware players will honor this rotation metadata.

Or, to answer your original question, you can rotate your videos as you transcode them. HandBrake has a filter for this which you can access using `transcode-video.sh` with the `--filter` option. You would use it like this:

    transcode-video.sh --filter rotate[=MODE] "/path/to/Movie.mkv"

...where `MODE` is an integer with one of four values:

* `1` for vertical flip
* `2` for horizontal flip
* `3` for both vertical and horizontal flip (this is the default)
* `4` to rotate clockwise 90 degrees

So, you could perform a rotation with value `4` like this:

    transcode-video.sh --filter rotate=4 "/path/to/Movie.mkv"

I hope that helps.

Thanks again for your question. I'll close this issue now but feel free to continue commenting here.

**Closed by donmelton** 2015-01-13 16:53 UTC

**Comment by buscarini** [comment] 2015-01-14 07:46
Thanks! Actually I had seen this option, but I hadn't thought how this could solve it. Thanks for you help
